### ISSUE TITLE
License not picked up from config file and GPL3 license not reflected in license_title field

### ISSUE THREAD

**Issue by halloleo** [idlesign/makeapp#5]
Firstly, thanks for makeapp! A very promising tool!

### 1. License not picked up from config file

I have in my `~/.makeapp/makeapp.conf` the line:

```
license = gpl3
```

but when I run 

    makeapp new muddleme ./muddleme -d "..."

the license is not picked up from the config file (other fields like author are). The skeleton still contains the BSD license.

### 2. GPL3 license not reflected in license_title field

Also, when I set the license on the command line:

    makeapp new muddleme ./muddleme -d "..." -l gpl3

The field output shows:

```
...
    license: gpl3
    license_title: BSD 3-Clause License
...
```

It looks like `makeapp` takes the license from the  command line and applies it to the `license` field, but not the `license_title` field.

**Comment by idlesign** [comment]
Thank you. 
I'll try to check this out eventually. By the way: pull requests are welcome.

**Comment by idlesign** [comment]
Considered fixed in master. 
Feel free to reopen if required.
